### ISSUE TITLE
topcenter Reverse scroll 

### ISSUE THREAD

**Issue by mukyasa** [ParsifalC/CPCollectionViewWheelLayoutSwift#1]
Hello ParsifalC,

When i set wheeltype = topcenter the scroll is reverse scroll , can you help me to improve the scroll(Proper scroll)

**Comment by ParsifalC** [comment]
@mukyasa  Thanks for your comments.I'll be glad to do it.The the layout direction is vertical now.You want it horizontal?Right?

**Comment by mukyasa** [comment]
I think so it already horizontal, but the scroll direction is reversed, means if i swipe left the collectionview scrolls to right and vice versa.

**Comment by ParsifalC** [comment]
Yeah.I got it.I will fix it in 20 minutes.

**Comment by ParsifalC** [comment]
@mukyasa YO!Checkout this [repo](https://github.com/ParsifalC/CPCollectionViewKit).I think it's ok now.

**Comment by ParsifalC** [comment]
😄Don't forget to star it if you like.

**Comment by mukyasa** [comment]
Sure Bro, Thanks for quick response ,

**Comment by ParsifalC** [comment]
Alright.
1.invisibleCellCount 2.attributes.center 3.contentSize
Here's the core codes.
```swift
        if configuration.wheelType == .bottomCenter || configuration.wheelType == .topCenter {
            invisibleCellCount = Double(collectionView.contentOffset.x/configuration.cellSize.width)
        } else {
            invisibleCellCount = Double(collectionView.contentOffset.y/configuration.cellSize.height)
        }
```

```swift
        case .topCenter:
            attributes.center = CGPoint(x: contentOffset.x+(viewSize.width)/2.0, y: (contentOffset.y)+cellSize.height/2)
  
```

```swift
        case .bottomCenter,.topCenter:
            visibleCellCount = CGFloat(180.0/configuration.angular+1.0)
            contentSize = CGSize(width: (viewSize.width)+(CGFloat(cellCount)-visibleCellCount)*(configuration.cellSize.width)+CGFloat(configuration.contentHeigthPadding), height:viewSize.height)
```

**Comment by ParsifalC** [comment]
It was a vertical layout before.But it's horizontal now.
